name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 23
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn -B package --file "IntelliJ IDEA/homework-solutions-Softwaretechnik-24-25-Uni-Koeln/homework_7/pom.xml"

      # Step 4: Run unit tests
      - name: Run tests
        run: mvn -B test --file "IntelliJ IDEA/homework-solutions-Softwaretechnik-24-25-Uni-Koeln/homework_7/pom.xml"
