name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step 3: Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn install

      # Step 4: Run JUnit tests
      - name: Run tests
        run: mvn test

      # Step 5: Generate test coverage report using JaCoCo
      - name: Generate JaCoCo coverage report
        run: mvn jacoco:report

      # Step 6: Build Docker image
      - name: Build Docker image
        run: docker build -t my-docker-image:latest .

      # Step 7: Run Docker container
      - name: Run Docker container
        run: docker run -d -p 8080:8080 my-docker-image:latest

      # Step 9: Upload coverage report as artifact
      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/site/jacoco/
