name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the latest code
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'

    # Step 3: Install Maven dependencies
    - name: Install dependencies
      run: mvn install

    # Step 4: Run JUnit tests
    - name: Run tests
      run: mvn test

    # Step 5: Generate test coverage report using JaCoCo
    - name: Generate coverage report
      run: mvn jacoco:report

    # Step 6: Upload JaCoCo coverage report as artifact
    - name:
