name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: List all files to find the pom.xml
      - name: List all files
        run: ls -R

      # Step 3: Set up Java 23
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Step 4: Build the project with Maven
      - name: Build with Maven
        run: mvn -B package --file homework_7/pom.xml

      # Step 5: Run tests
      - name: Run tests
        run: mvn -B test --file homework_7/pom.xml
