name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Install dependencies and build project
      - name: Install dependencies
        run: mvn dependency:resolve
        
      - name: Build project
        run: cd homework_7 && mvn clean package


      # Run tests
      - name: Run unit tests
        run: mvn test

      # Generate test coverage report
      - name: Generate JaCoCo report
        run: mvn jacoco:report
